version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - jenkins

  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins

  sonarqube:
    image: sonarqube:latest
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - "9000:9000"
    networks:
      - jenkins

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - jenkins

networks:
  jenkins:

volumes:
  jenkins-data:
