version: '3.8'

services:
  jenkins:
    build: ./jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - jenkins

  sonarqube:
    image: sonarqube:latest
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - "9000:9000"
    networks:
      - jenkins

  webapp:
    build: ./webapp
    ports:
      - "5000:5000"
    networks:
      - jenkins

networks:
  jenkins:

volumes:
  jenkins-data:
